### ISSUE TITLE
Special Character requirement not respected

### ISSUE THREAD

**Issue by Cookizza** [dermellor/mage-configurable-paswordstrength#4]
Hey there,

We've got the 'Must have special characters' rule set to 'yes' however users can still setup accounts using the password 'Password1' (has caps, has number) - given our config this shouldn't happen.

Magento 1.9.1 CE

Any thoughts?

**Comment by Cookizza** [comment]
My regex isn't great, but it seems like perhaps if there's a number present in the password, it doesn't care about symbols

**Comment by tuyennn** [comment]
@Cookizza 
See my pull [request](https://github.com/dermellor/mage-configurable-paswordstrength/pull/5) to fix your issue
